baseURL: "https://hubertlin.me/"
title: Hubert Lin
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: 
disqusShortname: "hubertlin"

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: posts
      name: Blog Posts
      url: /posts
      weight: 10
    # - identifier: Projects
    #   name: Projects
    #   url: /index
    #   weight: 20

params:
  env: production
  title: Hubert Lin
  description: "Hubert's blogs and projects"
  author: Me
  # images: ["<link or path of image for opengraph, twitter-cards>"]

  defaultTheme: auto # auto|dark|light
  # disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  # disableSpecial1stPost: false
  comments: true
  # hidemeta: false
  # showtoc: false
  # tocopen: false

  # Search #
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
  profileMode:
    enabled: true
    title: "Hubert Lin"
    subtitle: "Software Developer"
    imageUrl: "" # optional
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Blog Posts
        url: "/posts"

  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/linhub15"
    - name: "github"
      url: "https://github.com/linhub15"
    - name: "linkedin"
      url: "https://linkedin.com/in/linhub"