name: Production deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: hugo
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Deploy
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "_site"
